[alias]
# Build SERVER with default features 
bs = "build --features server --target-dir=target/server"
# Run SERVER with default features
rs = "run --features server --target-dir=target/server"
# Build SERVER with release optimizations
brs = "build --release --no-default-features --features server --target-dir=target/server"
# Run SERVER with release optimizations
rrs = "run --release --no-default-features --features server --target-dir=target/server"

# Build SPECTATOR_CLIENT with default features
bc = "build --features spectator_client --target-dir=target/client"
# Run SPECTATOR_CLIENT with default features
rc = "run --features spectator_client --target-dir=target/client"
# Build SPECTATOR_CLIENT with release optimizations
brc = "build --release --no-default-features --features spectator_client --target-dir=target/client"
# Run SPECTATOR_CLIENT with release optimizations
rrc = "run --release --no-default-features --features spectator_client --target-dir=target/client"
